// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokedex.PkdxDatabase.Context;

namespace PkdxDatabase.Migrations
{
    [DbContext(typeof(PokedexDBContext))]
    partial class PokedexDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pokedex.PkdxDatabase.Models.PokedexClass", b =>
                {
                    b.Property<float>("ID")
                        .HasColumnType("real");

                    b.Property<string>("Ability1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ability2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EggGroup1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EggGroup2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvolveMethod")
                        .HasColumnType("int");

                    b.Property<string>("HiddenAbility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PokedexEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
